# name: Build and deploy (DockerHub)

# on:
#     push:
#         branches:
#             - backend

# jobs:
#     build-and-deploy:
#         runs-on: ubuntu-latest
#         environment: production

#         steps:
#         - name: Telegram notification (start)
#           env:
#             BOT_TOKEN: "${{ secrets.TELEGRAM_BOT_TOKEN }}"
#             USER_IDS: "${{ secrets.TELEGRAM_CHAT_ID }}"
#           run: |
#             MESSAGE="Deploy starting:%0ARepo: $GITHUB_REPOSITORY%0ABranch: $GITHUB_REF_NAME%0AAuthor: $GITHUB_ACTOR"
#             for USER_ID in $USER_IDS; do
#                 curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
#                 -d chat_id="$USER_ID" \
#                 -d text="$MESSAGE"
#             done

#         - name: Checkout code
#           uses: actions/checkout@v3
#           with:
#             fetch-depth: 0
        
#         - name: Log in to Docker Hub
#           uses: docker/login-action@v3
#           with:
#             username: ${{ secrets.DOCKER_USERNAME }}
#             password: ${{ secrets.DOCKER_PASSWORD }}

#         - name: Build and push Docker image
#           uses: docker/build-push-action@v5
#           with:
#             context: .
#             push: true
#             tags: ${{ secrets.DOCKER_USERNAME }}/donormate:latest
#           cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/donormate:latest
#           cache-to: type=inline
          